name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Build the node docker image
        run: |
          docker build ./node --tag mohammadbelbesi99/super-app-node:latest
          docker tag mohammadbelbesi99/super-app-node:latest mohammadbelbesi99/super-app-node:${{ github.run_number}}-${{ github.sha }}

      - name: Build the php docker image
        run: |
          docker build ./php --tag mohammadbelbesi99/super-app-php:latest
          docker tag mohammadbelbesi99/super-app-php:latest mohammadbelbesi99/super-app-php:${{ github.run_number}}-${{ github.sha }}
      
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Push node docker image to registry
        run: |
          docker push mohammadbelbesi99/super-app-node:${{ github.run_number}}-${{ github.sha }}
          docker push mohammadbelbesi99/super-app-node:latest
      
      - name: Push php docker image to registry
        run: |
          docker push mohammadbelbesi99/super-app-php:${{ github.run_number}}-${{ github.sha }}
          docker push mohammadbelbesi99/super-app-php:latest

